tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "python@3.9"
brew "cmake"
brew "git"
brew "go"
brew "graphviz"
brew "luajit", args: ["HEAD"]
brew "mono"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "tmux"
brew "vim"
cask "blackhole-2ch"
